import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, Bot, Sparkles, History } from "lucide-react";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { AiQaList, type AiQaItem } from "@/components/community/ai-qa-list";

export const dynamic = "force-dynamic";

export default async function MyAiQaHistoryPage() {
  const supabase = await createServerSupabaseClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/signin?mode=sign-in");

  const userId = user.id;

  const [{ count, error: countError }, { data }] = await Promise.all([
    supabase
      .from("student_ai_qa")
      .select("id", { count: "exact", head: true })
      .eq("user_id", userId),
    supabase
      .from("student_ai_qa")
      .select("id, question, answer, model, is_saved, created_at")
      .eq("user_id", userId)
      .order("created_at", { ascending: false })
      .limit(100),
  ]);

  const total = countError ? 0 : (count ?? 0);
  const savedCount = (data ?? []).filter((r) => r.is_saved).length;

  const items: AiQaItem[] = (data ?? []).map((r) => ({
    id: String(r.id),
    question: String(r.question ?? ""),
    answer: String(r.answer ?? ""),
    model: r.model ? String(r.model) : null,
    isSaved: Boolean(r.is_saved),
    createdAt: String(r.created_at ?? new Date().toISOString()),
  }));

  return (
    <div>
      <Link
        href="/community/ask"
        className="inline-flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-ink dark:text-slate-300 dark:hover:text-white"
      >
        <ArrowLeft className="h-4 w-4" /> Back to Community
      </Link>

      <div className="mt-6 flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-purple-100 text-purple-700 dark:bg-purple-950/50">
            <History className="h-6 w-6" />
          </div>
          <div>
            <h1 className="text-2xl font-black text-primary">My AI Questions</h1>
            <p className="mt-1 text-sm text-secondary">
              Every question you ask the CalibiAI Assistant is saved here so you can revisit the
              answers anytime.
            </p>
          </div>
        </div>
        <Link
          href="/community/create?type=question"
          className="inline-flex items-center gap-2 rounded-full bg-purple-600 px-5 py-2.5 text-sm font-bold text-white shadow-soft transition-all hover:-translate-y-0.5 hover:bg-purple-700"
        >
          <Bot className="h-4 w-4" /> Ask AI
        </Link>
      </div>

      <div className="mt-6 grid gap-4 sm:grid-cols-3">
        <div className="glass-panel p-4 text-center">
          <p className="text-2xl font-black text-purple-700 dark:text-purple-300">{total}</p>
          <p className="text-sm text-subtle">Total Questions</p>
        </div>
        <div className="glass-panel p-4 text-center">
          <p className="text-2xl font-black text-amber-600 dark:text-amber-300">{savedCount}</p>
          <p className="text-sm text-subtle">Saved</p>
        </div>
        <div className="glass-panel p-4 text-center">
          <p className="text-2xl font-black text-brand-700 dark:text-brand-300">
            {total > 0 ? Math.round((savedCount / total) * 100) : 0}%
          </p>
          <p className="text-sm text-subtle">Save Rate</p>
        </div>
      </div>

      <div className="mt-2 flex items-center gap-2 text-xs text-subtle">
        <Sparkles className="h-3.5 w-3.5 text-purple-500" />
        Answers are generated by CalibiAI Assistant and stored privately for your account only.
      </div>

      <AiQaList items={items} />
    </div>
  );
}
