import crypto from "crypto";
import fs from "fs";
import path from "path";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { ROLE_DETAILS, isLearningRole, type LearningRole } from "@/lib/learning/content";

type Question = { id:string; topic:string; skill:string; difficulty:"Easy"|"Medium"; weight:number; question:string; options:string[]; correct_answer:number; explanation:string; roadmap_reference:string };
type Bank = { assessment:{ skills_assessed:string[] }; questions:Question[] };
type Attempt = { id:string; role:LearningRole; seed:string; question_ids:string[]; answers:Record<string,number>; answer_results:Record<string,{is_correct:boolean}> };
export type Result<T>={data:T;error:null}|{data:null;error:{message:string;status?:number}};
const banks = new Map<LearningRole,Bank>();
function bank(role:LearningRole): Bank { const cached=banks.get(role); if (cached) return cached; const value=JSON.parse(fs.readFileSync(path.join(process.cwd(),"content/assessment",ROLE_DETAILS[role].assessmentFile),"utf8")) as Bank; const bySkill=new Map<string,number>(); value.questions.forEach(q=>bySkill.set(q.skill,(bySkill.get(q.skill)??0)+1)); if(value.assessment.skills_assessed.length!==10||[...bySkill.values()].some(n=>n<2)) throw new Error("Assessment bank schema is incomplete."); banks.set(role,value); return value; }
function rng(seed:string) { let value=0; for(const char of seed) value=(value*31+char.charCodeAt(0))>>>0; return ()=>((value=(value*1664525+1013904223)>>>0)/4294967296); }
function pick<T>(items:T[], random:()=>number,n:number){const copy=[...items];const result:T[]=[];while(result.length<n&&copy.length)result.push(copy.splice(Math.floor(random()*copy.length),1)[0]!);return result;}
function selected(role:LearningRole,seed:string) { const content=bank(role), random=rng(seed); const ids=content.assessment.skills_assessed.flatMap(skill=>{const qs=content.questions.filter(q=>q.skill===skill);const medium=qs.filter(q=>q.difficulty==="Medium"), easy=qs.filter(q=>q.difficulty==="Easy"); return medium.length&&easy.length?[pick(easy,random,1)[0]!,pick(medium,random,1)[0]!]:pick(qs,random,2);}).map(q=>q.id); return pick(ids,random,ids.length); }
function publicQuestion(question:Question){const {correct_answer,explanation,roadmap_reference,weight,...safe}=question;return safe;}
async function userAndRole(){const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user) return {supabase,user:null,role:null}; const {data:profile}=await supabase.from("profiles").select("learning_role").eq("user_id",user.id).single();return {supabase,user,role:isLearningRole(profile?.learning_role)?profile.learning_role:null};}
export async function startAttempt():Promise<Result<{attemptId:string;questions:ReturnType<typeof publicQuestion>[];answers:Record<string,number>}>> { const {supabase,user,role}=await userAndRole(); if(!user||!role)return {data:null,error:{message:"Complete onboarding before starting the assessment.",status:401}}; const {data:active}=await supabase.from("assessment_results").select("id,seed,question_ids,answers").eq("user_id",user.id).eq("role",role).eq("status","in_progress").maybeSingle(); let row=active; if(!row){const {count}=await supabase.from("assessment_results").select("id",{count:"exact",head:true}).eq("user_id",user.id).eq("role",role); const seed=crypto.randomUUID();const {data,error}=await supabase.from("assessment_results").insert({user_id:user.id,role,attempt_number:(count??0)+1,seed,question_ids:selected(role,seed),status:"in_progress"}).select("id,seed,question_ids,answers").single();if(error||!data)return {data:null,error:{message:"Could not start your assessment."}};row=data;} const lookup=new Map(bank(role).questions.map(q=>[q.id,q]));return {data:{attemptId:row.id,questions:(row.question_ids as string[]).map(id=>publicQuestion(lookup.get(id)!)),answers:(row.answers??{}) as Record<string,number>},error:null}; }
export async function recordAnswer(attemptId:string,questionId:string,selectedIndex:number):Promise<Result<{correct_answer:number;is_correct:boolean;explanation:string}>> {if(!Number.isInteger(selectedIndex)||selectedIndex<0||selectedIndex>3)return {data:null,error:{message:"Invalid answer option.",status:422}};const {supabase,user}=await userAndRole();if(!user)return {data:null,error:{message:"Please sign in again.",status:401}};const {data:row}=await supabase.from("assessment_results").select("id,role,status,question_ids,answers,answer_results").eq("id",attemptId).eq("user_id",user.id).maybeSingle();if(!row||row.status!=="in_progress"||!isLearningRole(row.role)||(row.question_ids as string[]).includes(questionId)===false)return {data:null,error:{message:"Assessment question was not found.",status:404}};const question=bank(row.role).questions.find(q=>q.id===questionId)!;const answers=(row.answers??{}) as Record<string,number>;const results=(row.answer_results??{}) as Record<string,{is_correct:boolean}>;if(answers[questionId]!==undefined)return {data:{correct_answer:question.correct_answer,is_correct:results[questionId]!.is_correct,explanation:question.explanation},error:null};answers[questionId]=selectedIndex;results[questionId]={is_correct:selectedIndex===question.correct_answer};const {error}=await supabase.from("assessment_results").update({answers,answer_results:results}).eq("id",attemptId).eq("status","in_progress");if(error)return {data:null,error:{message:"Could not record your answer."}};return {data:{correct_answer:question.correct_answer,is_correct:results[questionId]!.is_correct,explanation:question.explanation},error:null};}
export async function finishAttempt(attemptId:string):Promise<Result<{overall:number;level:string;skillScores:{skill:string;score:number;band:string}[]}>> {const {supabase,user}=await userAndRole();if(!user)return {data:null,error:{message:"Please sign in again.",status:401}};const {data:row}=await supabase.from("assessment_results").select("*").eq("id",attemptId).eq("user_id",user.id).maybeSingle() as {data:Attempt|null};if(!row||!isLearningRole(row.role))return {data:null,error:{message:"Assessment not found.",status:404}};const qs=(row.question_ids).map(id=>bank(row.role).questions.find(q=>q.id===id)!);if(Object.keys(row.answers??{}).length!==qs.length)return {data:null,error:{message:"Answer every question before finishing.",status:422}};const skillScores=bank(row.role).assessment.skills_assessed.map(skill=>{const own=qs.filter(q=>q.skill===skill);const possible=own.reduce((n,q)=>n+(q.difficulty==="Medium"?1.3:1),0);const earned=own.reduce((n,q)=>n+(row.answer_results[q.id]?.is_correct?(q.difficulty==="Medium"?1.3:1):0),0);const score=Math.round(100*earned/possible);return {skill,score,band:score<40?"weak":score<75?"developing":"strong"};});const overall=Math.round(skillScores.reduce((n,s)=>n+s.score,0)/skillScores.length);const weak=skillScores.filter(s=>s.band==="weak").sort((a,b)=>a.score-b.score);const strong=skillScores.filter(s=>s.band==="strong").sort((a,b)=>b.score-a.score);const level=overall>=70&&strong.length>=6&&weak.length<=1?"intermediate":"beginner";const roadmapFile=ROLE_DETAILS[row.role].roadmap[level as "beginner"|"intermediate"]; const roadmap=JSON.parse(fs.readFileSync(path.join(process.cwd(),"content/roadmap",roadmapFile),"utf8")) as {days:{day:number;title:string;skills_gained?:string[]}[]}; const graph={role:row.role,level,overall,skills:skillScores.map(s=>({...s,related_days:roadmap.days.filter(day=>[day.title,...(day.skills_gained??[])].some(text=>text.toLowerCase().includes(s.skill.toLowerCase())||s.skill.toLowerCase().includes(text.toLowerCase()))).map(day=>day.day),recommendation:s.band==="weak"?"reinforce":s.band==="strong"?"compress":"keep"})),weak_skills:weak.map(s=>s.skill),strong_skills:strong.map(s=>s.skill),generated_at:new Date().toISOString()};await supabase.from("assessment_results").update({status:"submitted",overall_score:overall,level,submitted_at:new Date().toISOString()}).eq("id",attemptId);await supabase.from("skill_scores").upsert(skillScores.map(s=>({assessment_result_id:attemptId,user_id:user.id,...s})),{onConflict:"assessment_result_id,skill"});await supabase.from("knowledge_graph").upsert({assessment_result_id:attemptId,user_id:user.id,graph},{onConflict:"assessment_result_id"});return {data:{overall,level,skillScores},error:null};}
