"use client";
import { AnimatePresence, motion } from "framer-motion";
import { Check, ChevronLeft, Github, Loader2 } from "lucide-react";
import { useMemo, useState } from "react";
import type { LearningRole } from "@/lib/learning/content";

type Props = { initialStep: number; initialProfile: Record<string, unknown>; roles: { id: LearningRole; title: string; description: string; icon: string; skills: string[] }[] };
const steps = ["Welcome", "Profile", "Role", "Connect", "Ready"];
async function save(body: object) { const response = await fetch("/api/onboarding", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok || result.error) throw new Error(result.error?.message ?? "Unable to save your progress."); return result; }

export function OnboardingWizard({ initialStep, initialProfile, roles }: Props) {
 const [step, setStep] = useState(Math.min(5, Math.max(1, initialStep || 1))); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
 const [profile, setProfile] = useState({ full_name: String(initialProfile.full_name ?? ""), display_name: String(initialProfile.display_name ?? ""), country: String(initialProfile.country ?? ""), timezone: String(initialProfile.timezone ?? (Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC")), education_level: String(initialProfile.education_level ?? ""), experience_level: String(initialProfile.experience_level ?? ""), weekly_hours: Number(initialProfile.weekly_hours ?? 10) });
 const [role, setRole] = useState<LearningRole | "">(initialProfile.learning_role as LearningRole ?? ""); const [github, setGithub] = useState(String(initialProfile.github_username ?? ""));
 const valid = useMemo(() => step !== 2 || (profile.full_name.trim().length >= 2 && profile.country && profile.education_level && profile.experience_level && profile.weekly_hours >= 3), [step, profile]);
 const advance = async (skipConnect = false) => { setError(""); setBusy(true); try { if (step === 2) await save({ step: 3, profile }); else if (step === 3) { if (!role) throw new Error("Choose a career role to continue."); await save({ step: 4, role }); } else if (step === 4) { if (github) await save({ githubUsername: github }); await save({ step: 5, skippedConnect: skipConnect }); } else await save({ step: Math.min(5, step + 1) }); setStep(Math.min(5, step + 1)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save."); } finally { setBusy(false); } };
 const body = <AnimatePresence mode="wait"><motion.div key={step} initial={{ opacity: 0, x: 24 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -24 }} transition={{ duration: .22 }}>
 {step === 1 && <><p className="text-sm font-bold text-brand-600">Welcome to CalibiAI</p><h1 className="mt-3 text-3xl font-black text-primary">Let&apos;s build your personalized 45-day path.</h1><p className="mt-4 text-secondary">We&apos;ll tailor your learning plan in about four minutes—starting with a short placement assessment.</p></>}
 {step === 2 && <><h1 className="text-2xl font-black text-primary">Tell us about you</h1><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Full name *" value={profile.full_name} onChange={v=>setProfile({...profile,full_name:v})}/><Field label="Display name" value={profile.display_name} onChange={v=>setProfile({...profile,display_name:v})}/><Select label="Country *" value={profile.country} onChange={v=>setProfile({...profile,country:v})} options={["IN:India","US:United States","GB:United Kingdom","CA:Canada","AU:Australia","OTHER:Other"]}/><Field label="Timezone" value={profile.timezone} onChange={v=>setProfile({...profile,timezone:v})}/><Select label="Education level *" value={profile.education_level} onChange={v=>setProfile({...profile,education_level:v})} options={["High School","Undergraduate","Graduate","Professional"]}/><Select label="Experience level *" value={profile.experience_level} onChange={v=>setProfile({...profile,experience_level:v})} options={["New to tech","Some coding","Experienced"]}/></div><label className="label mt-4 block">Weekly hours: <b>{profile.weekly_hours}</b></label><input className="mt-2 w-full accent-blue-600" type="range" min="3" max="40" value={profile.weekly_hours} onChange={e=>setProfile({...profile,weekly_hours:Number(e.target.value)})}/></>}
 {step === 3 && <><h1 className="text-2xl font-black text-primary">Choose your AI career role</h1><p className="mt-2 text-secondary">This selects your assessment and roadmap family.</p><div className="mt-5 grid gap-3 sm:grid-cols-2" role="radiogroup">{roles.map(item=><button type="button" role="radio" aria-checked={role===item.id} onClick={()=>setRole(item.id)} key={item.id} className={`rounded-2xl border p-4 text-left transition ${role===item.id ? "border-brand-500 bg-brand-50 dark:bg-brand-950/30" : "border-slate-200 dark:border-slate-700"}`}><span className="text-2xl">{item.icon}</span><h2 className="mt-2 font-bold text-primary">{item.title} {role===item.id && <Check className="inline h-4 text-brand-600"/>}</h2><p className="mt-1 text-sm text-secondary">{item.description}</p><div className="mt-3 flex flex-wrap gap-1">{item.skills.slice(0,3).map(skill=><span key={skill} className="rounded-full bg-slate-100 px-2 py-1 text-xs dark:bg-slate-800">{skill}</span>)}</div></button>)}</div></>}
 {step === 4 && <><h1 className="text-2xl font-black text-primary">Connect your profile</h1><p className="mt-2 text-secondary">Optional signals can personalize your recommendations. You can always connect them later.</p><label className="label mt-5 block">GitHub username</label><div className="mt-1 flex gap-2"><div className="input flex items-center gap-2 py-0"><Github className="h-4"/><input className="w-full bg-transparent py-3 outline-none" placeholder="octocat" value={github} onChange={e=>setGithub(e.target.value)}/></div></div><label className="label mt-4 block">LinkedIn or resume</label><p className="mt-1 text-sm text-secondary">Resume upload and LinkedIn linking will be available from Settings. Your information is used only to personalize learning.</p></>}
 {step === 5 && <><p className="text-sm font-bold text-brand-600">You&apos;re ready</p><h1 className="mt-2 text-3xl font-black text-primary">Start your placement assessment.</h1><div className="mt-5 rounded-2xl bg-brand-50 p-5 text-brand-950 dark:bg-brand-950/30 dark:text-brand-100"><p className="font-bold">20 questions · about 10 minutes</p><p className="mt-1 text-sm">It isn&apos;t pass/fail. It simply helps us place you on the right path.</p></div></>}
 </motion.div></AnimatePresence>;
 return <main className="min-h-screen bg-gradient-to-br from-brand-50 via-white to-indigo-50 px-4 py-10 dark:from-slate-950 dark:via-slate-950 dark:to-indigo-950"><section className="mx-auto max-w-2xl rounded-3xl border border-slate-200 bg-white p-6 shadow-xl dark:border-slate-800 dark:bg-slate-900 sm:p-9"><div className="mb-8"><div className="flex justify-between text-xs font-bold text-secondary">{steps.map((name,i)=><span className={i+1===step?"text-brand-600":""} key={name}>{name}</span>)}</div><div className="mt-3 flex gap-1">{steps.map((_,i)=><div key={i} className={`h-2 flex-1 rounded-full ${i+1<=step?"bg-brand-500":"bg-slate-200 dark:bg-slate-700"}`}/>)}</div></div>{body}{error && <p role="alert" className="mt-5 text-sm font-medium text-rose-600">{error}</p>}<div className="mt-8 flex items-center justify-between gap-3">{step>1?<button type="button" className="btn-ghost" onClick={()=>setStep(step-1)} disabled={busy}><ChevronLeft className="h-4"/> Back</button>:<span/>}{step===5?<a className="btn-primary" href="/assessment">Start Assessment</a>:<div className="flex gap-2">{step===4&&<button type="button" className="btn-ghost" disabled={busy} onClick={()=>advance(true)}>Skip for now</button>}<button type="button" className="btn-primary" disabled={!valid||busy} onClick={()=>advance(false)}>{busy&&<Loader2 className="h-4 animate-spin"/>}{step===1?"Get started":"Continue"}</button></div>}</div></section></main>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}) { return <label className="label">{label}<input className="input mt-1" value={value} onChange={e=>onChange(e.target.value)}/></label> }
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[]}) { return <label className="label">{label}<select className="input mt-1" value={value} onChange={e=>onChange(e.target.value)}><option value="">Select…</option>{options.map(option=>{const [key,name]=option.split(":");return <option key={option} value={key}>{name??key}</option>})}</select></label> }
