-- ============================================================
-- 00_reset
-- DEV-ONLY. Truncates every seeded table + auth.users rows created by the seed.
-- Auto-generated by supabase/seed/scripts/generate_seed.py
-- ============================================================

-- Guard: refuse to run against a Supabase project marked "prod".
DO $$
BEGIN
  IF current_setting('app.environment', true) = 'production' THEN
    RAISE EXCEPTION 'Refusing to reset seed data in production.';
  END IF;
END $$;

BEGIN;
SET LOCAL session_replication_role = replica;

TRUNCATE
  public.seed_activity_log,
  public.seed_login_history,
  public.seed_weekly_user_xp,
  public.seed_weekly_platform_stats,
  public.seed_daily_missions,
  public.seed_github_stats,
  public.comm_member_badges,
  public.comm_comment_votes,
  public.comm_post_votes,
  public.comm_post_saves,
  public.comm_comments,
  public.comm_posts,
  public.comm_follows,
  public.comm_members,
  public.comm_xp,
  public.projects,
  public.scores
RESTART IDENTITY CASCADE;

-- Only remove seed profiles (identified by the seed marker in raw_user_meta_data)
DELETE FROM public.profiles
WHERE user_id IN (
  SELECT id FROM auth.users
  WHERE raw_user_meta_data->>'seed' = 'true'
);

DELETE FROM auth.identities
WHERE user_id IN (
  SELECT id FROM auth.users
  WHERE raw_user_meta_data->>'seed' = 'true'
);

DELETE FROM auth.users WHERE raw_user_meta_data->>'seed' = 'true';

COMMIT;
