-- ============================================================
-- 04_communities
-- 20 curated communities with slugs, banners, colors, and trending metadata. Compatible with existing comm_communities schema.
-- Auto-generated by supabase/seed/scripts/generate_seed.py
-- ============================================================
INSERT INTO public.comm_communities (id, slug, name, emoji, description, cover_color, banner_url, sort_order, is_active, created_at) VALUES
  ('cd09057b-2e00-5008-bf82-60f795f093e4', 'general-ai', 'General AI', '🤖', 'Everything about artificial intelligence — news, trends, and open discussions.', '#1f8fff', '/storage/community-banners/general-ai.png', 1, true, '2025-08-24T00:00:00+00:00'),
  ('ef39291b-3d75-5436-9532-9681f6b38c38', 'prompt-engineering', 'Prompt Engineering', '🧠', 'Master the art and science of prompting LLMs effectively.', '#f45f8a', '/storage/community-banners/prompt-engineering.png', 2, true, '2025-08-24T00:00:00+00:00'),
  ('bc5889d4-b624-565d-a5e3-c19e37ebd2d4', 'llms', 'LLMs', '🦜', 'Large Language Models — GPT, Claude, Gemini, Llama, Mistral and more.', '#8b5cf6', '/storage/community-banners/llms.png', 3, true, '2025-08-24T00:00:00+00:00'),
  ('d2461814-a1b4-5d0c-aa4b-0cb78f318d7a', 'rag', 'RAG', '📚', 'Retrieval-Augmented Generation patterns, tools, and best practices.', '#22c55e', '/storage/community-banners/rag.png', 4, true, '2025-08-24T00:00:00+00:00'),
  ('4e3de4cf-4eb8-598d-8142-bbcc14d9b202', 'ai-agents', 'AI Agents', '🕹️', 'Autonomous AI agents, LangGraph, CrewAI, AutoGen and frameworks.', '#eab308', '/storage/community-banners/ai-agents.png', 5, true, '2025-08-24T00:00:00+00:00'),
  ('3f1a1f30-af94-55b7-9c8b-07689768982e', 'mcp', 'MCP', '🔌', 'Model Context Protocol — standards, tools, and integrations.', '#f97316', '/storage/community-banners/mcp.png', 6, true, '2025-08-24T00:00:00+00:00'),
  ('a231fb57-c92c-5df8-82f7-228f4f45a8e0', 'langgraph', 'LangGraph', '🕸️', 'Graph-based orchestration for stateful, tool-using agents.', '#06b6d4', '/storage/community-banners/langgraph.png', 7, true, '2025-08-24T00:00:00+00:00'),
  ('5beb3241-b2c7-5c2e-aa18-6406082369f5', 'crewai', 'CrewAI', '🧑‍🤝‍🧑', 'Role-based multi-agent teams that ship real work.', '#a855f7', '/storage/community-banners/crewai.png', 8, true, '2025-08-24T00:00:00+00:00'),
  ('72fe25a8-5002-54ef-ab07-5a0e27bb17f8', 'n8n', 'n8n', '⚡', 'Low-code AI automations, workflows and integrations.', '#10b981', '/storage/community-banners/n8n.png', 9, true, '2025-08-24T00:00:00+00:00'),
  ('2916b543-829f-55f6-af95-472e196f6ff8', 'make', 'Make (Integromat)', '🧩', 'Visual automation and AI workflows on Make.', '#ef4444', '/storage/community-banners/make.png', 10, true, '2025-08-24T00:00:00+00:00'),
  ('5d5ca41b-f1b4-5c09-b441-6aaaa4c3c45d', 'python', 'Python', '🐍', 'Python for AI development — libraries, tips, and projects.', '#1f8fff', '/storage/community-banners/python.png', 11, true, '2025-08-24T00:00:00+00:00'),
  ('cacd79c0-29ad-5054-844e-94574a2dd70d', 'deep-learning', 'Deep Learning', '🧬', 'Neural nets, transformers, training tricks and papers.', '#f45f8a', '/storage/community-banners/deep-learning.png', 12, true, '2025-08-24T00:00:00+00:00'),
  ('87cc79bc-7b47-5fba-a44b-d984288111f2', 'machine-learning', 'Machine Learning', '📈', 'Classical ML, feature engineering, and applied problems.', '#8b5cf6', '/storage/community-banners/machine-learning.png', 13, true, '2025-08-24T00:00:00+00:00'),
  ('be46ad5f-9d16-50ac-8990-947aa0555782', 'computer-vision', 'Computer Vision', '👁️', 'Vision models, YOLO, CLIP, segmentation and OCR.', '#22c55e', '/storage/community-banners/computer-vision.png', 14, true, '2025-08-24T00:00:00+00:00'),
  ('0eb8dd37-2b34-56d4-bcdb-3c21311fa7a5', 'openai', 'OpenAI', '🟢', 'GPT-4o, Realtime, function calling, Assistants API tips.', '#eab308', '/storage/community-banners/openai.png', 15, true, '2025-08-24T00:00:00+00:00'),
  ('ca9fa564-89d3-5dc0-8bf4-5c2c91a927c0', 'claude', 'Claude', '🟣', 'Anthropic Claude — long context, tool use, and best prompts.', '#f97316', '/storage/community-banners/claude.png', 16, true, '2025-08-24T00:00:00+00:00'),
  ('bbaa6298-6293-5fae-9cb7-04ca25018b52', 'gemini', 'Gemini', '🔷', 'Google Gemini models, Vertex AI and Google Cloud AI.', '#06b6d4', '/storage/community-banners/gemini.png', 17, true, '2025-08-24T00:00:00+00:00'),
  ('bf35d528-fbe2-5152-8c78-170c1ea2f788', 'mistral', 'Mistral', '🟠', 'Mistral open models, fine-tuning and deployments.', '#a855f7', '/storage/community-banners/mistral.png', 18, true, '2025-08-24T00:00:00+00:00'),
  ('0e88206f-12d7-5ba0-9138-c8c8d6bda5d7', 'vector-databases', 'Vector Databases', '🧭', 'Pinecone, Weaviate, Qdrant, pgvector — indexes and tuning.', '#10b981', '/storage/community-banners/vector-databases.png', 19, true, '2025-08-24T00:00:00+00:00'),
  ('89bc4550-fa74-588a-9deb-86d1c190df3f', 'hugging-face', 'Hugging Face', '🤗', 'Transformers, datasets, spaces and open-source models.', '#ef4444', '/storage/community-banners/hugging-face.png', 20, true, '2025-08-24T00:00:00+00:00')
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, banner_url = EXCLUDED.banner_url, cover_color = EXCLUDED.cover_color;
