-- ============================================================
-- 12_badges
-- Badge catalog. Uses ON CONFLICT to be safe with the existing seed in migration 002.
-- Auto-generated by supabase/seed/scripts/generate_seed.py
-- ============================================================
INSERT INTO public.comm_badges (id, slug, name, description, emoji, category) VALUES
  ('a619bc87-42d2-5acb-ae3a-b060b46ec73f', 'top-contributor', 'Top Contributor', 'Top 1% contributor by community XP for the month.', '🌟', 'special'),
  ('638c8189-3faa-5a45-8a57-287ecae31514', 'prompt-master', 'Prompt Master', 'Delivered 25+ high-signal prompt patterns to the community.', '🧠', 'skill'),
  ('846e765f-7d4f-5644-9b6c-1c5454062cda', 'ai-builder', 'AI Builder', 'Shipped 5+ verified AI projects.', '🛠️', 'skill'),
  ('87ac483b-832d-5fb4-97a8-a059659a9e79', 'production-ready', 'Production Ready', 'Passed assessment, roadmap, capstone, GitHub and portfolio checks.', '🚀', 'special'),
  ('b1f65728-8f73-5205-8af9-2f6fab1435a2', 'streak-100', '100-Day Streak', 'Learned or contributed on 100 consecutive days.', '🔥', 'milestone'),
  ('ddb3f58b-9e41-5b91-997d-fb5cc4a2fcc9', 'rag-expert', 'RAG Expert', 'Verified expertise in retrieval-augmented systems.', '📚', 'skill'),
  ('4194b168-b934-5706-b789-5a4cc9678ff7', 'community-helper', 'Community Helper', 'Answered 50+ questions with helpful, accepted responses.', '🤝', 'contribution'),
  ('10a2eced-6b90-5192-87c6-930d3b77c5e6', 'hackathon-winner', 'Hackathon Winner', 'Won or podiumed at a CalibiAI hackathon.', '🏆', 'special'),
  ('2334f73d-4323-5b4d-ae33-e5e0f0f19a0b', 'weekly-winner', 'Weekly Winner', 'Topped the weekly XP leaderboard.', '🥇', 'special'),
  ('8400d40e-c009-5385-ba9a-75cccc27a20e', 'top-mentor', 'Top Mentor', 'Recognized as a top mentor by the community.', '🎓', 'contribution')
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, emoji = EXCLUDED.emoji, category = EXCLUDED.category;
