-- ============================================================
-- 20_recalc
-- Reconciles denormalized counters after bulk inserts and computes trending / weekly-activity scores for communities.
-- Auto-generated by supabase/seed/scripts/generate_seed.py
-- ============================================================

-- Recompute member_count and post_count from source of truth
UPDATE public.comm_communities c SET
  member_count = COALESCE(m.n, 0),
  post_count   = COALESCE(p.n, 0),
  weekly_activity = COALESCE(w.n, 0),
  trending_score = COALESCE((
    SELECT (SUM(pp.upvotes) * 1.0 + SUM(pp.comment_count) * 1.5 + SUM(pp.view_count) * 0.05)
    FROM public.comm_posts pp
    WHERE pp.community_id = c.id
      AND pp.created_at >= now() - interval '14 days'
  ), 0)
FROM (
  SELECT community_id, COUNT(*)::int n
  FROM public.comm_members GROUP BY community_id
) m
FULL OUTER JOIN (
  SELECT community_id, COUNT(*)::int n
  FROM public.comm_posts GROUP BY community_id
) p ON p.community_id = m.community_id
FULL OUTER JOIN (
  SELECT community_id, COUNT(*)::int n
  FROM public.comm_posts
  WHERE created_at >= now() - interval '7 days'
  GROUP BY community_id
) w ON w.community_id = COALESCE(m.community_id, p.community_id)
WHERE c.id = COALESCE(m.community_id, p.community_id, w.community_id);

-- Reconcile comment_count / save_count on posts (in case triggers were bypassed)
UPDATE public.comm_posts p SET
  comment_count = COALESCE(cc.n, 0),
  save_count    = COALESCE(sc.n, 0)
FROM (
  SELECT post_id, COUNT(*)::int n FROM public.comm_comments GROUP BY post_id
) cc
FULL OUTER JOIN (
  SELECT post_id, COUNT(*)::int n FROM public.comm_post_saves GROUP BY post_id
) sc ON sc.post_id = cc.post_id
WHERE p.id = COALESCE(cc.post_id, sc.post_id);

-- Reconcile followers_count / following_count on profiles
UPDATE public.profiles pr SET
  followers_count = COALESCE(fc.n, 0),
  following_count = COALESCE(fg.n, 0)
FROM (
  SELECT following_id user_id, COUNT(*)::int n
  FROM public.comm_follows GROUP BY following_id
) fc
FULL OUTER JOIN (
  SELECT follower_id user_id, COUNT(*)::int n
  FROM public.comm_follows GROUP BY follower_id
) fg USING (user_id)
WHERE pr.user_id = fc.user_id OR pr.user_id = fg.user_id;

-- Refresh leaderboards
SELECT public.refresh_leaderboards();

-- Sanity checks
DO $$
DECLARE cnt integer;
BEGIN
  SELECT COUNT(*) INTO cnt FROM public.profiles;      RAISE NOTICE 'profiles: %', cnt;
  SELECT COUNT(*) INTO cnt FROM public.comm_communities; RAISE NOTICE 'communities: %', cnt;
  SELECT COUNT(*) INTO cnt FROM public.comm_posts;    RAISE NOTICE 'posts: %', cnt;
  SELECT COUNT(*) INTO cnt FROM public.comm_comments; RAISE NOTICE 'comments: %', cnt;
  SELECT COUNT(*) INTO cnt FROM public.comm_post_votes; RAISE NOTICE 'likes: %', cnt;
  SELECT COUNT(*) INTO cnt FROM public.comm_post_saves; RAISE NOTICE 'bookmarks: %', cnt;
  SELECT COUNT(*) INTO cnt FROM public.comm_follows;   RAISE NOTICE 'follows: %', cnt;
  SELECT COUNT(*) INTO cnt FROM public.projects;       RAISE NOTICE 'projects: %', cnt;
  SELECT COUNT(*) INTO cnt FROM public.seed_activity_log; RAISE NOTICE 'activities: %', cnt;
  SELECT COUNT(*) INTO cnt FROM public.seed_login_history; RAISE NOTICE 'logins: %', cnt;
END $$;
