-- ============================================================
-- 99_seed_all
-- Runs every seed file in dependency order in a single transaction. Requires the service_role connection (bypasses RLS).
-- Auto-generated by supabase/seed/scripts/generate_seed.py
-- ============================================================
BEGIN;
SET LOCAL search_path = public;
SET LOCAL statement_timeout = '10min';

\i 01_auth_users.sql
\i 02_profiles.sql
\i 03_scores.sql
\i 04_communities.sql
\i 05_community_members.sql
\i 06_posts.sql
\i 07_comments.sql
\i 08_post_votes.sql
\i 09_post_saves.sql
\i 10_follows.sql
\i 11_projects.sql
\i 12_badges.sql
\i 13_member_badges.sql
\i 14_xp.sql
\i 15_activity_log.sql
\i 16_daily_missions.sql
\i 17_login_history.sql
\i 18_weekly_stats.sql
\i 19_github_stats.sql
\i 20_recalc.sql

COMMIT;
