-- Core catalog, assignment, weekly-review, and Bedrock audit schema.
CREATE TABLE IF NOT EXISTS public.user_roadmaps (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, roadmap_id uuid REFERENCES public.roadmaps(id) ON DELETE SET NULL, role text NOT NULL, level text NOT NULL CHECK(level IN ('beginner','intermediate')), version integer NOT NULL DEFAULT 1, status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','archived','completed')), personalization jsonb NOT NULL DEFAULT '{"sequence":[],"day_actions":{},"focus_skills":[],"version":1}'::jsonb, start_date date NOT NULL DEFAULT current_date, last_review_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS one_active_learning_roadmap ON public.user_roadmaps(user_id, role) WHERE status='active';
ALTER TABLE public.roadmap_progress ADD COLUMN IF NOT EXISTS user_roadmap_id uuid REFERENCES public.user_roadmaps(id) ON DELETE CASCADE, ADD COLUMN IF NOT EXISTS day integer, ADD COLUMN IF NOT EXISTS prereq_days integer[] NOT NULL DEFAULT '{}', ADD COLUMN IF NOT EXISTS unlock_at timestamptz;
CREATE UNIQUE INDEX IF NOT EXISTS roadmap_progress_day_idx ON public.roadmap_progress(user_roadmap_id, day) WHERE user_roadmap_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS public.weekly_reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, week_index integer NOT NULL, input jsonb NOT NULL, output jsonb NOT NULL, ai_enriched boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,week_index));
CREATE TABLE IF NOT EXISTS public.ai_invocations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, agent text NOT NULL, model text, tokens_in integer NOT NULL DEFAULT 0, tokens_out integer NOT NULL DEFAULT 0, latency_ms integer NOT NULL DEFAULT 0, cache_hit boolean NOT NULL DEFAULT false, status text NOT NULL CHECK(status IN ('ok','fallback','error')), created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.user_roadmaps ENABLE ROW LEVEL SECURITY; ALTER TABLE public.weekly_reports ENABLE ROW LEVEL SECURITY; ALTER TABLE public.ai_invocations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_roadmaps_own" ON public.user_roadmaps FOR ALL USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);
CREATE POLICY "weekly_reports_own" ON public.weekly_reports FOR ALL USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);
CREATE POLICY "ai_invocations_own_read" ON public.ai_invocations FOR SELECT USING(auth.uid()=user_id);
