-- ============================================================
-- 020_seed_support_tables
-- Adds seed-support tables: activity log, daily missions, login history, weekly platform stats, weekly user XP, GitHub profile stats, and materialized leaderboards.
-- Auto-generated by supabase/seed/scripts/generate_seed.py
-- ============================================================

-- Activity log ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.seed_activity_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  activity_type text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_seed_activity_log_user_time
  ON public.seed_activity_log (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_seed_activity_log_type
  ON public.seed_activity_log (activity_type);
ALTER TABLE public.seed_activity_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "seed_activity_read_self" ON public.seed_activity_log
  FOR SELECT USING (auth.uid() = user_id OR public.current_user_role() = 'admin');
CREATE POLICY "seed_activity_admin_write" ON public.seed_activity_log
  FOR ALL USING (public.current_user_role() = 'admin')
  WITH CHECK (public.current_user_role() = 'admin');

-- Daily missions -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.seed_daily_missions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text UNIQUE NOT NULL,
  title text NOT NULL,
  category text NOT NULL,
  xp_reward integer NOT NULL DEFAULT 10,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.seed_daily_missions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "seed_missions_read" ON public.seed_daily_missions FOR SELECT USING (true);
CREATE POLICY "seed_missions_admin_write" ON public.seed_daily_missions
  FOR ALL USING (public.current_user_role() = 'admin')
  WITH CHECK (public.current_user_role() = 'admin');

-- Login history --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.seed_login_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  logged_in_at timestamptz NOT NULL,
  time_band text NOT NULL CHECK (time_band IN ('morning','afternoon','night')),
  device text NOT NULL DEFAULT 'web',
  ip_country text
);
CREATE INDEX IF NOT EXISTS idx_seed_login_history_user_time
  ON public.seed_login_history (user_id, logged_in_at DESC);
CREATE INDEX IF NOT EXISTS idx_seed_login_history_time
  ON public.seed_login_history (logged_in_at DESC);
ALTER TABLE public.seed_login_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "seed_login_read_self" ON public.seed_login_history
  FOR SELECT USING (auth.uid() = user_id OR public.current_user_role() = 'admin');
CREATE POLICY "seed_login_admin_write" ON public.seed_login_history
  FOR ALL USING (public.current_user_role() = 'admin')
  WITH CHECK (public.current_user_role() = 'admin');

-- Weekly stats ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.seed_weekly_platform_stats (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  week_index integer NOT NULL,
  week_start date NOT NULL,
  week_end date NOT NULL,
  posts_created integer NOT NULL DEFAULT 0,
  comments_created integer NOT NULL DEFAULT 0,
  signups integer NOT NULL DEFAULT 0,
  active_users integer NOT NULL DEFAULT 0,
  weekday_learning_events integer NOT NULL DEFAULT 0,
  weekend_project_events integer NOT NULL DEFAULT 0,
  UNIQUE (week_start)
);
CREATE TABLE IF NOT EXISTS public.seed_weekly_user_xp (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  week_index integer NOT NULL,
  week_start date NOT NULL,
  xp integer NOT NULL DEFAULT 0,
  UNIQUE (user_id, week_start)
);
CREATE INDEX IF NOT EXISTS idx_seed_weekly_user_xp_user
  ON public.seed_weekly_user_xp (user_id, week_start);

-- GitHub stats snapshot ------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.seed_github_stats (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  repository_count integer NOT NULL DEFAULT 0,
  contribution_count integer NOT NULL DEFAULT 0,
  stars_received integer NOT NULL DEFAULT 0,
  stars_given integer NOT NULL DEFAULT 0,
  languages text[] NOT NULL DEFAULT '{}',
  pinned_projects jsonb NOT NULL DEFAULT '[]'::jsonb,
  open_source_score integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.seed_github_stats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "seed_github_read" ON public.seed_github_stats FOR SELECT USING (true);
CREATE POLICY "seed_github_admin_write" ON public.seed_github_stats
  FOR ALL USING (public.current_user_role() = 'admin')
  WITH CHECK (public.current_user_role() = 'admin');

-- Denormalized profile extension (city/state, engagement counters, connections)
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS state text,
  ADD COLUMN IF NOT EXISTS country text DEFAULT 'India',
  ADD COLUMN IF NOT EXISTS learning_path text,
  ADD COLUMN IF NOT EXISTS current_role text,
  ADD COLUMN IF NOT EXISTS assessment_score integer,
  ADD COLUMN IF NOT EXISTS talent_score integer,
  ADD COLUMN IF NOT EXISTS talent_tier text,
  ADD COLUMN IF NOT EXISTS xp integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS weekly_xp integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS community_xp integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS projects_completed integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS assignments_completed integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS current_streak integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS longest_streak integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS followers_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS following_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS current_level integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS github_connected boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS linkedin_connected boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_production_ready boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS last_login timestamptz;

-- Communities: enrich comm_communities with banner + trending
ALTER TABLE public.comm_communities
  ADD COLUMN IF NOT EXISTS banner_url text,
  ADD COLUMN IF NOT EXISTS trending_score numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS weekly_activity integer NOT NULL DEFAULT 0;

-- Materialized views for leaderboards (refresh nightly in production)
CREATE MATERIALIZED VIEW IF NOT EXISTS public.mv_leaderboard_talent AS
SELECT p.user_id, p.username, p.full_name, p.avatar_url,
       p.talent_score, p.talent_tier
FROM public.profiles p
WHERE p.flagged = false
ORDER BY p.talent_score DESC NULLS LAST
LIMIT 200;

CREATE MATERIALIZED VIEW IF NOT EXISTS public.mv_leaderboard_weekly_xp AS
SELECT p.user_id, p.username, p.full_name, p.avatar_url, p.weekly_xp
FROM public.profiles p
WHERE p.flagged = false
ORDER BY p.weekly_xp DESC NULLS LAST
LIMIT 200;

CREATE MATERIALIZED VIEW IF NOT EXISTS public.mv_leaderboard_community_xp AS
SELECT p.user_id, p.username, p.full_name, p.avatar_url, p.community_xp
FROM public.profiles p
WHERE p.flagged = false
ORDER BY p.community_xp DESC NULLS LAST
LIMIT 200;

CREATE MATERIALIZED VIEW IF NOT EXISTS public.mv_leaderboard_streak AS
SELECT p.user_id, p.username, p.full_name, p.avatar_url,
       p.current_streak, p.longest_streak
FROM public.profiles p
WHERE p.flagged = false
ORDER BY p.current_streak DESC NULLS LAST
LIMIT 200;

CREATE MATERIALIZED VIEW IF NOT EXISTS public.mv_leaderboard_projects AS
SELECT p.user_id, p.username, p.full_name, p.avatar_url,
       p.projects_completed
FROM public.profiles p
WHERE p.flagged = false
ORDER BY p.projects_completed DESC NULLS LAST
LIMIT 200;

CREATE MATERIALIZED VIEW IF NOT EXISTS public.mv_leaderboard_github AS
SELECT p.user_id, p.username, p.full_name, p.avatar_url,
       g.open_source_score, g.repository_count, g.stars_received
FROM public.profiles p
JOIN public.seed_github_stats g ON g.user_id = p.user_id
WHERE p.flagged = false
ORDER BY g.open_source_score DESC NULLS LAST
LIMIT 200;

-- Helper: refresh all leaderboards
CREATE OR REPLACE FUNCTION public.refresh_leaderboards()
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  REFRESH MATERIALIZED VIEW public.mv_leaderboard_talent;
  REFRESH MATERIALIZED VIEW public.mv_leaderboard_weekly_xp;
  REFRESH MATERIALIZED VIEW public.mv_leaderboard_community_xp;
  REFRESH MATERIALIZED VIEW public.mv_leaderboard_streak;
  REFRESH MATERIALIZED VIEW public.mv_leaderboard_projects;
  REFRESH MATERIALIZED VIEW public.mv_leaderboard_github;
END;
$$;
